services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    networks:
      - front-tier

  vote:
    image: 211125460791.dkr.ecr.eu-central-1.amazonaws.com/peja-vote-repo:${VOTE_TAG}
    networks: 
      - front-tier
      - back-tier

  result:
    image: 211125460791.dkr.ecr.eu-central-1.amazonaws.com/peja-result-repo:${RESULT_TAG}
    networks: 
      - front-tier
      - back-tier

  worker:
    image: 211125460791.dkr.ecr.eu-central-1.amazonaws.com/peja-worker-repo:${WORKER_TAG}
    networks: 
      - back-tier

  redis:
    image: redis:alpine
    networks: 
      - back-tier

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks: 
      - back-tier

volumes:
  db-data:

networks:
  front-tier: 
  back-tier:  